# Generated by Django 4.2.9 on 2024-03-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
