# Generated by Django 4.2.9 on 2024-03-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
