# Generated by Django 4.2.9 on 2024-03-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_alter_customuser_groups_alter_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
