# Generated by Django 4.2.9 on 2024-03-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_rename_password_reset_token_user_reset_password_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
