# Generated by Django 4.2.9 on 2024-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('MyApp', '0018_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reset_password_token',
            new_name='reset_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token_created',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='myapp_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='myapp_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
