# Generated by Django 4.2.9 on 2024-04-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='indio',
        ),
    ]
