# Generated by Django 4.2.9 on 2024-04-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_rename_photo_indio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='indio',
            new_name='photos',
        ),
    ]
