# Generated by Django 4.2.9 on 2024-04-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_rename_indio_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photos',
            new_name='Photo',
        ),
    ]
