# Generated by Django 4.2.9 on 2024-04-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_rename_photos_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Indio_Solari',
        ),
    ]
