# Generated by Django 4.2.9 on 2024-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_ciro_divididos_la_renga_laspelotas_ntvg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indio_solari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Indio_Solari/'),
        ),
    ]
