# Generated by Django 4.2.9 on 2024-04-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_alter_indio_solari_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ntvg',
            new_name='notvg',
        ),
    ]
