# Generated by Django 4.2.9 on 2024-04-14 00:43

import MyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_alter_notvg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyApp.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='divididos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyApp.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='indio_solari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyApp.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='la_renga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyApp.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='laspelotas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyApp.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='notvg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyApp.models.image_upload_path),
        ),
    ]
